name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality gates (Pint + PHPStan + Tests)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
          coverage: none
          extensions: mbstring, xml, sqlite3, pdo_sqlite, fileinfo, openssl

      - name: Cache Composer downloads
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --ansi

      - name: Pint (code style)
        run: vendor/bin/pint --test

      - name: PHPStan (static analysis)
        run: vendor/bin/phpstan analyse --no-progress --ansi

      - name: Tests (Pest)
        run: php artisan test --no-interaction --ansi
